<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="public/css/bootstrap.min.css">
    <title>Cadastro de Produto</title>
</head>
<body>
    <div class="container mt-4">
        <h1>Cadastro de Produto</h1>
        <form action="produtos/cadastrar" method="POST">
            <div class="mb-3">
                <label for="descricao" class="form-label">Descrição</label>
                <input type="text" class="form-control" name="descricao" id="descricao" required>
            </div>
            <div class="mb-3">
                <label for="valorVenda" class="form-label">Valor de Venda</label>
                <input type="number" step="0.01" class="form-control" name="valorVenda" id="valorVenda" required>
            </div>
            <div class="mb-3">
                <label for="estoque" class="form-label">Estoque</label>
                <input type="number" class="form-control" name="estoque" id="estoque" required>
            </div>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
    </div>
    <script src="public/js/bootstrap.min.js"></script>
</body>
</html>
