<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="public/css/bootstrap.min.css">
    <title>Lista de Produtos</title>
</head>
<body>
    <div class="container mt-4">
        <h1>Produtos</h1>
        <a href="produtos/cadastrar" class="btn btn-primary mb-3">Cadastro de Produto</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Descrição</th>
                    <th>Valor de Venda</th>
                    <th>Estoque</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($produtos): ?>
                    <?php while ($produto = $produtos->fetch_assoc()): ?>
                        <tr>
                            <td><?php echo $produto['id']; ?></td>
                            <td><?php echo $produto['descricao']; ?></td>
                            <td><?php echo $produto['valorVenda']; ?></td>
                            <td><?php echo $produto['estoque']; ?></td>
                            <td>
                                <a href="produtos/editar/<?php echo $produto['ID']; ?>" class="btn btn-warning">Editar</a>
                                <a href="produtos/excluir/<?php echo $produto['ID']; ?>" class="btn btn-danger">Excluir</a>
                            </td>
                        </tr>
                    <?php endwhile; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="4">Nenhum produto encontrado</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
    <script src="public/js/bootstrap.min.js"></script>
</body>
</html>
